[package]
name = "s3-access-log-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
http = "1.0.0"
http-serde = "2.0.0"
serde = { version = "1.0.195", features = ["derive"] }
