use serde::Deserialize;
use csv::ReaderBuilder;

use http::StatusCode;
use std::net::IpAddr;
use std::net::Ipv4Addr;

#[derive(Debug, Deserialize,PartialEq)]
struct WscRecord {
    bucket_owner: String,
    bucket_name: String,
    time: String,
    remote_ip: IpAddr,
    requester: String, //The canonical user ID of the requester, or a - for unauthenticated requests. If the requester was an IAM user, this field returns the requester's IAM user name along with the AWS account root user that the IAM user belongs to. This identifier is the same one used for access control purposes.
    request_id: String, //A string generated by Amazon S3 to uniquely identify each request.
    operation: String,
    key: String,
    request_uri: String,
    #[serde(with = "http_serde::status_code")]
    http_status: StatusCode,
    error_code: String,
    bytes_sent: String, // The number of response bytes sent, excluding HTTP protocol overhead, or - if zero. WTF !!!
    object_size: String, // can also be - but the doc don't mention it !!!
    total_time: String,
    turn_around_time: String,
    referer: String,
    user_agent: String,
    version_id: String,
    host_id: String,
    signature_version: String,
    cipher_suite: String,
    authentication_type: String,
    host_header: String,
    tls_version: String,
    access_point_arn: String,
    acl_required: String
}


#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        let expected_result = WscRecord {bucket_owner : "7e1c2dcc1527ebbd9a81efbefb6a7d5945b7c6fe00160f682c2b7c056d301e83".to_string(),
        bucket_name: "aws-website-demonchy-5v3aj".to_string(),
        time: "11/Nov/2023:03:37:50 +0000".to_string(),
        remote_ip: std::net::IpAddr::V4(Ipv4Addr::new(130,176,48,151)),
        requester: "-".to_string(),
        request_id: "YDYP07R0QHFNH76W".to_string(),
        operation: "WEBSITE.GET.OBJECT".to_string(),
        key: "favicon.ico".to_string(),
        request_uri: "GET /favicon.ico HTTP/1.1".to_string(),
        http_status: StatusCode::NOT_FOUND,
        error_code: "NoSuchKey".to_string(),
        bytes_sent: "346".to_string(),
        object_size: "-".to_string(),
        total_time: "39".to_string(),
        turn_around_time: "-".to_string(),
        referer: "-".to_string(),
        user_agent: "Amazon CloudFront".to_string(),
        version_id: "-".to_string(),
        host_id: "m3PGwDN1s8smqpOSEELewHILMcdm7xri7/UsWHBhRrT0w23Pp0YcEmgboXyHFTv7qR7RvFMrUgo=".to_string(),
        signature_version: "-".to_string(),
        cipher_suite: "-".to_string(),
        authentication_type: "-".to_string(),
        host_header: "aws-website-demonchy-5v3aj.s3-website-us-east-1.amazonaws.com".to_string(),
        tls_version: "-".to_string(),
        access_point_arn: "-".to_string(),
        acl_required: "-".to_string()
    };
        let wsv = "7e1c2dcc1527ebbd9a81efbefb6a7d5945b7c6fe00160f682c2b7c056d301e83 aws-website-demonchy-5v3aj [11/Nov/2023:03:37:50 +0000] 130.176.48.151 - YDYP07R0QHFNH76W WEBSITE.GET.OBJECT favicon.ico \"GET /favicon.ico HTTP/1.1\" 404 NoSuchKey 346 - 39 - \"-\" \"Amazon CloudFront\" - m3PGwDN1s8smqpOSEELewHILMcdm7xri7/UsWHBhRrT0w23Pp0YcEmgboXyHFTv7qR7RvFMrUgo= - - - aws-website-demonchy-5v3aj.s3-website-us-east-1.amazonaws.com - - -";
        let valid_wsv = wsv.replace("[", "\"").replace("]", "\"");
        let mut reader = ReaderBuilder::new().has_headers(false).delimiter(b' ').from_reader(valid_wsv.as_bytes());
        for result in reader.deserialize::<WscRecord>() {
            assert_eq!(result.unwrap(), expected_result);
        }
    }
}
